[BladeLLM] [CI] Add BladeLLM e2e tests (#173)

diff --git a/.github/workflows/bench_test.yml b/.github/workflows/bench_test.yml
--- a/.github/workflows/bench_test.yml
+++ b/.github/workflows/bench_test.yml
@@ -17,9 +17,9 @@ jobs:
       with:
         all_but_latest: true
 
-  bench_test:
+  vllm_bench_test:
     needs: cancel_previous_workflows
-    runs-on: [self-hosted]
+    runs-on: [self-hosted,non-rdma]
     timeout-minutes: 90
     steps:
     - name: Checkout
@@ -29,6 +29,37 @@ jobs:
         [[ -n $(docker ps -q) ]] && docker kill $(docker ps -q) || echo "No running containers to kill."
     - name: Build And Test
       run: ./tools/run_test.sh vllm_bench_test
+    - name: Create comment from file
+      if: ${{ github.event_name != 'push' }}
+      uses: actions/github-script@v7
+      with:
+        script: |
+          try {
+            const fs = require('fs');
+            const filePath = 'performance.txt';
+            const commentBody = fs.readFileSync(filePath, 'utf8');
+            await github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: commentBody
+            });
+          } catch (error) {
+            console.log('Failed to create comment:', error.message);
+          }
+
+  bladellm_bench_test:
+    needs: cancel_previous_workflows
+    runs-on: [self-hosted,rdma]
+    timeout-minutes: 120
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+    - name: Kill Running Containers
+      run: |
+        [[ -n $(docker ps -q) ]] && docker kill $(docker ps -q) || echo "No running containers to kill."
+    - name: Build And Test
+      run: ./tools/run_test.sh bladellm_bench_test
     - name: Create comment from file
       if: ${{ github.event_name != 'push' }}
       uses: actions/github-script@v7
